
name: Build Flutter App
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App Name"
        required: true
      package_name:
        description: "Package Name"
        required: true
      app_url:
        description: "Website URL"
        required: true
      version:
        description: "App Version"
        required: false
        default: "1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          
      - name: Flutter doctor
        run: flutter doctor -v
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release --verbose
        
      - name: Build AAB
        run: flutter build appbundle --release --verbose
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
          
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 30
